// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCTpaC9O7YkfEZyTYQ7luz8sR6ckFxyAo',
    appId: '1:505169481131:web:dd1562fc2422d46096d6ee',
    messagingSenderId: '505169481131',
    projectId: 'fir-db172',
    authDomain: 'fir-db172.firebaseapp.com',
    storageBucket: 'fir-db172.appspot.com',
    measurementId: 'G-PL7VVLZ2JW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUdOBPN0MBcy06I-pMgsrXuooj5YKtE98',
    appId: '1:505169481131:android:ae4608fc0197713a96d6ee',
    messagingSenderId: '505169481131',
    projectId: 'fir-db172',
    storageBucket: 'fir-db172.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_jq02x_9IyHvzmOBxMriBEAwtR2Ipz7A',
    appId: '1:505169481131:ios:8669d8c29b7a87ee96d6ee',
    messagingSenderId: '505169481131',
    projectId: 'fir-db172',
    storageBucket: 'fir-db172.appspot.com',
    iosBundleId: 'com.example.demoAgoraUiKit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_jq02x_9IyHvzmOBxMriBEAwtR2Ipz7A',
    appId: '1:505169481131:ios:8a42a95d48ae08ec96d6ee',
    messagingSenderId: '505169481131',
    projectId: 'fir-db172',
    storageBucket: 'fir-db172.appspot.com',
    iosBundleId: 'com.example.demoAgoraUiKit.RunnerTests',
  );
}
